# Generated by Django 5.1 on 2025-12-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="კატეგორიის სახელი"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="კოდი"),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("hvac", "გათბობა/გაგრილება (HVAC)"),
                            ("ventilation", "ვენტილაცია"),
                            ("refrigeration", "სამაცივრო"),
                            ("electrical", "ელექტრო"),
                            ("plumbing", "სანტექნიკა"),
                            ("other", "სხვა"),
                        ],
                        default="hvac",
                        max_length=50,
                        verbose_name="სისტემის ტიპი",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-gear",
                        help_text="Bootstrap Icons კლასი, მაგ: bi-fan, bi-thermometer",
                        max_length=50,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="HEX ფერი, მაგ: #ff5733",
                        max_length=20,
                        verbose_name="ფერი",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="აღწერა")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
            ],
            options={
                "verbose_name": "კატეგორია",
                "verbose_name_plural": "კატეგორიები",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["site", "category", "name"],
                "verbose_name": "მოწყობილობა",
                "verbose_name_plural": "მოწყობილობები",
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="installation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="ინსტალაციის თარიღი"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location_detail",
            field=models.CharField(
                blank=True,
                help_text="მაგ: სახურავი, სარდაფი, მე-2 სართული",
                max_length=200,
                verbose_name="ზუსტი მდებარეობა",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="model_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="მოდელი"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="შენიშვნები"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "აქტიური"),
                    ("inactive", "არააქტიური"),
                    ("maintenance", "მომსახურებაში"),
                    ("broken", "გაფუჭებული"),
                ],
                default="active",
                max_length=20,
                verbose_name="სტატუსი",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="გარანტიის ვადა"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="brand",
            field=models.CharField(blank=True, max_length=100, verbose_name="ბრენდი"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=200, verbose_name="სახელი"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="სერიული ნომერი"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("heating_cooling", "გათბობა/გაგრილება"),
                    ("ventilation", "ვენტილაცია"),
                ],
                max_length=50,
                verbose_name="სისტემის ტიპი",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="companies.equipmentcategory",
                verbose_name="კატეგორია",
            ),
        ),
    ]
