# Generated by Django 5.1 on 2025-12-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "დავალება მინიჭებული"),
                    ("task_due", "ვადა იწურება"),
                    ("task_overdue", "ვადა გასული"),
                    ("task_completed", "დავალება დასრულდა"),
                    ("task_approved", "დავალება დამტკიცდა"),
                    ("task_rejected", "დავალება უარყოფილია"),
                    ("system", "სისტემური"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
